[tool.ruff]
line-length = 88
target-version = "py311"

[tool.ruff.lint]
# E: pycodestyle (PEP 8), F: pyflakes, I: isort (import sorting)
select = ["E", "F", "I"]
ignore = [
    "E501",  # line-length handled by formatter
]

[tool.ruff.format]
# Black-compatible formatting
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
